# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  # name of the builder
  inherited_builder:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:inherited_builder/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["inheritedBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: { ".dart": ["inherited_builder.g.part"] }
    # Will automatically run on any package that depends on it
    auto_apply: all_packages
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
